title: Astar Network Status Page
author: Astar Foundation
description: >- # this means to ignore newlines until "baseurl:"
  Astar Network Status Page contains and up-to-date information and announcements related to 
   netowrk performance and technical updates such as new releases for 
  Shiden and Astar Networks.
# baseurl: "network-status" # the subpath of your site, e.g. /blog
# url: "https://astarnetwork.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: AstarNetwork
github_username:  AstarNetwork

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y %H:%M"
